__title__       = "RiveScript Playground"
__version__     = "1.0.0"
__author__      = "Noah Petherbridge"
__email__       = "root@kirsle.net"
__description__ = "Test, develop and share RiveScript snippets."
__license__     = "GPL"
